"""Flashcard module added

Revision ID: 260386fbfa39
Revises: aad212d1e107
Create Date: 2026-07-21 17:00:13.666914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260386fbfa39'
down_revision = 'aad212d1e107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=500), nullable=False),
    sa.Column('back', sa.String(length=1000), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_subject_id'))

    op.drop_table('flashcards')
    # ### end Alembic commands ###
