"""Added Liibrary Module

Revision ID: 642b847df30c
Revises: 8fada2449349
Create Date: 2026-07-24 10:45:09.031513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642b847df30c'
down_revision = '8fada2449349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('creator', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_items_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_cache_subject_id'))

    op.drop_table('resource_cache')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resources_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('resources_json')

    op.create_table('resource_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('keywords_json', sa.TEXT(), nullable=False),
    sa.Column('videos_json', sa.TEXT(), nullable=False),
    sa.Column('books_json', sa.TEXT(), nullable=False),
    sa.Column('fetched_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_cache_subject_id'), ['subject_id'], unique=1)

    with op.batch_alter_table('library_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_library_items_subject_id'))

    op.drop_table('library_items')
    # ### end Alembic commands ###
