"""Timetable module added

Revision ID: 876e68e2edd8
Revises: e0809b3b330b
Create Date: 2026-07-23 10:50:23.160015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876e68e2edd8'
down_revision = 'e0809b3b330b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetable_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timetable_entries_user_id'))

    op.drop_table('timetable_entries')
    # ### end Alembic commands ###
