"""ResourceCache added

Revision ID: 8fada2449349
Revises: c5c4014ee2a7
Create Date: 2026-07-23 14:55:48.509742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fada2449349'
down_revision = 'c5c4014ee2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('videos_json', sa.Text(), nullable=False),
    sa.Column('books_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_cache_subject_id'), ['subject_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_cache_subject_id'))

    op.drop_table('resource_cache')
    # ### end Alembic commands ###
