"""linked studysession to timetableentry

Revision ID: 9ef432a05715
Revises: 642b847df30c
Create Date: 2026-07-27 09:40:31.019881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef432a05715'
down_revision = '642b847df30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('videos_json', sa.Text(), nullable=False),
    sa.Column('books_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_cache_subject_id'), ['subject_id'], unique=True)

    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timetable_entry_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_study_sessions_timetable_entry_id'), ['timetable_entry_id'], unique=False)
        batch_op.create_foreign_key('fk_study_sessions_timetable_entry_id', 'timetable_entries', ['timetable_entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_study_sessions_timetable_entry_id'))
        batch_op.drop_column('timetable_entry_id')

    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_cache_subject_id'))

    op.drop_table('resource_cache')
    # ### end Alembic commands ###
