"""QuizAttempt and QuizAttemptAnswer modules added

Revision ID: c5c4014ee2a7
Revises: 876e68e2edd8
Create Date: 2026-07-23 11:58:24.394847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c4014ee2a7'
down_revision = '876e68e2edd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('quiz_attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=1000), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_answers_attempt_id'), ['attempt_id'], unique=False)

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_column('user_answer')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answer', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_answers_attempt_id'))

    op.drop_table('quiz_attempt_answers')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))

    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
